In [6]:
from torch.nn import ReLU
import torch

input = torch.tensor([-2, -1, 0, 1, 2])
m = ReLU()
print(input)
output = m(input)
print(output)

tensor([-2, -1,  0,  1,  2])
tensor([0, 0, 0, 1, 2])


In [11]:
from torch.nn import Sigmoid
import torch

input = torch.tensor([-2, -1, 0, 1, 2], dtype=torch.float)
m = Sigmoid()
print(input)
output = m(input)
print(output)

tensor([-2., -1.,  0.,  1.,  2.])
tensor([0.1192, 0.2689, 0.5000, 0.7311, 0.8808])
